#!/bin/bash
set -e

HOOKS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$HOME/.claude/claude-office-config.env"

echo "Installing hooks from: $HOOKS_DIR"

# Check for uv
if ! command -v uv &> /dev/null; then
    echo "Error: 'uv' is not installed. Please install it first."
    exit 1
fi

# Default strip prefixes - strips common path prefixes from project names
DEFAULT_PREFIXES="-Users-$USER-Repos-,-Users-$USER-"

# Parse arguments
STRIP_PREFIXES=""
while [[ $# -gt 0 ]]; do
    case $1 in
        --strip-prefixes)
            STRIP_PREFIXES="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--strip-prefixes 'prefix1,prefix2']"
            exit 1
            ;;
    esac
done

# Use default if not specified
if [ -z "$STRIP_PREFIXES" ]; then
    STRIP_PREFIXES="$DEFAULT_PREFIXES"
    echo "Using default strip prefixes: $STRIP_PREFIXES"
else
    echo "Using custom strip prefixes: $STRIP_PREFIXES"
fi

# Create config directory if it doesn't exist
mkdir -p "$(dirname "$CONFIG_FILE")"

# Save configuration
echo "Saving configuration to $CONFIG_FILE..."
cat > "$CONFIG_FILE" << EOF
# Claude Office Hooks Configuration
# Generated by install.sh

# Prefixes to strip from project names in the session browser
# Edit this and restart Claude Code to change
CLAUDE_OFFICE_STRIP_PREFIXES="$STRIP_PREFIXES"

# Set to 1 to enable debug logging
CLAUDE_OFFICE_DEBUG=0
EOF

echo "Configuration saved."

# Install the python package as a tool
echo "Installing claude-office-hook tool..."
cd "$HOOKS_DIR"
uv tool install --force -p 3.14 .

# Use the command name directly - uv tool install adds it to PATH
# This is cross-platform compatible (works on macOS, Linux, and Windows)
HOOK_CMD="claude-office-hook"

# Verify the command is available
if ! command -v "$HOOK_CMD" &> /dev/null; then
    echo "Warning: '$HOOK_CMD' not found in PATH. You may need to add ~/.local/bin to your PATH."
    echo "Continuing with installation anyway..."
fi

echo "Configuring Claude settings..."

# Use the python script to manage settings safely
# Pass the hook command name (not full path) for cross-platform compatibility
uv run -p 3.14 "$HOOKS_DIR/manage_hooks.py" install --hook-cmd "$HOOK_CMD"

echo ""
echo "Done! Please restart Claude Code to apply changes."
echo ""
echo "Configuration file: $CONFIG_FILE"
echo "Edit this file to customize strip prefixes, then restart Claude Code."
