"""Agent dialogue quotes for office situations."""

import random

WORK_ACCEPTANCE_QUOTES: list[str] = [
    # Enthusiastic
    "On it!",
    "Let's go!",
    "Got it!",
    "Consider it done!",
    "Right away!",
    "I'm on it!",
    "Leave it to me!",
    "Say no more!",
    "You got it!",
    "Absolutely!",
    # Professional
    "Understood.",
    "Will do.",
    "Noted.",
    "Acknowledged.",
    "Affirmative.",
    "Copy that.",
    "Roger that.",
    "Right on.",
    "Certainly.",
    "Of course.",
    # Casual
    "Sure thing!",
    "No problem!",
    "Easy peasy!",
    "Piece of cake!",
    "I got this!",
    "Watch me!",
    "Here I go!",
    "Time to shine!",
    "My specialty!",
    "Born ready!",
    # Motivated
    "Challenge accepted!",
    "Bring it on!",
    "Let's do this!",
    "Game on!",
    "Ready to roll!",
    "Locked and loaded!",
    "Mission accepted!",
    "Full steam ahead!",
    "At your service!",
    "To the desk!",
    # Quirky
    "Ooh, fun!",
    "Finally!",
    "Yes! Love it!",
    "My time to shine!",
    "Perfecto!",
    "Excellent!",
    "Fantastic!",
    "Brilliant!",
    "Splendid!",
    "Marvelous!",
    # Determined
    "I won't let you down!",
    "Trust me on this.",
    "I've got your back!",
    "Count on me!",
    "This is my jam!",
    "Right up my alley!",
    "Made for this!",
    "This is what I do!",
    "Watch and learn!",
    "Stand back!",
    # Tech-themed
    "Compiling thoughts...",
    "Processing...",
    "Executing!",
    "Initializing!",
    "Loading solution...",
    "Crunching numbers!",
    "Analyzing...",
    "Optimizing!",
    "Deploying!",
    "Syncing up!",
    # Short and sweet
    "Yep!",
    "Done!",
    "Sure!",
    "Yes!",
    "K!",
    "Ok!",
    "Aye!",
    "Yup!",
    "Bet!",
    "Word!",
    # Office humor
    "Coffee first!",
    "After snacks!",
    "Overtime it is!",
    "Meeting-free zone!",
    "Inbox zero later!",
    "Deadline? What deadline?",
    "Hold my coffee!",
    "Peak productivity!",
    "Flow state incoming!",
    "Focus mode: ON",
    # Confident
    "Too easy!",
    "Child's play!",
    "Simple!",
    "Trivial!",
    "Quick work!",
    "Lightning speed!",
    "In a flash!",
    "Watch this!",
    "Nailed it!",
    "Crushed it!",
]


def get_random_work_acceptance_quote() -> str:
    """Return a random work acceptance quote."""
    return random.choice(WORK_ACCEPTANCE_QUOTES)


JOB_COMPLETION_QUOTES: list[str] = [
    # Classic completions
    "Everything looks perfect. Project complete!",
    "And that's a wrap! Great work everyone!",
    "Mission accomplished! Excellent job!",
    "All done! Time to celebrate!",
    "Finished! Another successful project!",
    "Complete! That was some fine work!",
    "Done and dusted! Well played, team!",
    "Project delivered! Outstanding effort!",
    "That's the last of it! Brilliant work!",
    "All tasks complete! Take a bow!",
    # Satisfied boss
    "Couldn't have done it better myself!",
    "This is exactly what I was looking for!",
    "Exceeded my expectations! Wonderful!",
    "Quality work across the board!",
    "I'm impressed! Really impressed!",
    "Top-notch execution, everyone!",
    "This is why I love this team!",
    "Flawless delivery! Well done!",
    "Perfection achieved! Bravo!",
    "You've outdone yourselves!",
    # Celebratory
    "Pop the confetti! We did it!",
    "Victory dance time! 🎉",
    "Success! Ring the bell!",
    "Another one in the books!",
    "Champagne-worthy work! 🍾",
    "Standing ovation deserved!",
    "Time to party! Job well done!",
    "High fives all around!",
    "Break out the snacks! We're done!",
    "Pizza party earned! 🍕",
    # Professional satisfaction
    "All requirements met. Shipping it!",
    "Tests pass. Looks clean. Perfect!",
    "Ready for production! Nice work!",
    "Client will love this! Great job!",
    "Under budget, on time. Legendary!",
    "Zero bugs found! Incredible!",
    "Smooth sailing from here!",
    "Deployment ready! Let's go live!",
    "Documentation complete! Ship it!",
    "Code review approved! Excellent!",
    # Casual boss
    "Nailed it! You all rock!",
    "That hit different! Amazing work!",
    "Chef's kiss! Absolutely perfect! 👨‍🍳",
    "No notes! It's beautiful!",
    "Send it! We're golden!",
    "Lock it in! Perfect execution!",
    "That's how it's done! Boom!",
    "Mic drop moment! 🎤",
    "Legendary status achieved!",
    "Built different! Love to see it!",
    # Tech-themed
    "Build succeeded! Pipeline green!",
    "All systems nominal! 🚀",
    "Commit merged! Release ready!",
    "Exit code 0! Pure success!",
    "100% test coverage! Beautiful!",
    "Linting passed! Clean code!",
    "Performance optimized! Snappy!",
    "Memory leaks: none! Perfect!",
    "Compilation complete! Flawless!",
    "CI/CD pipeline: all green! ✅",
    # Motivational
    "This is what excellence looks like!",
    "Teamwork makes the dream work!",
    "Together we conquer! Great job!",
    "Hard work pays off! Proud of you!",
    "Dreams become reality! Done!",
    "We aimed high and delivered!",
    "Challenge conquered! Moving on!",
    "Another mountain climbed!",
    "Persistence wins! Job complete!",
    "The grind was worth it!",
    # Relieved boss
    "Finally! It's perfect!",
    "We made it! What a journey!",
    "Phew! That was intense but worth it!",
    "Can't believe we pulled it off!",
    "Against all odds! Done!",
    "Deadline met! Crisis averted!",
    "Scope creep defeated! Victory!",
    "Stakeholders will be thrilled!",
    "Management will be pleased!",
    "Coffee paid off! Project done!",
    # Short and punchy
    "Perfect!",
    "Magnificent!",
    "Superb!",
    "Outstanding!",
    "Spectacular!",
    "Phenomenal!",
    "Incredible!",
    "Immaculate!",
    "Splendid!",
    "Marvelous!",
    # Playful
    "Bug-free zone achieved! 🐛❌",
    "Code so clean it sparkles! ✨",
    "Ready to make users happy!",
    "Future me will thank present us!",
    "That's what I call a masterpiece!",
    "Even the tests are impressed!",
    "The code gods are pleased!",
    "Rubber duck approved! 🦆",
    "Stack Overflow would be proud!",
    "10/10 would ship again!",
]


def get_random_job_completion_quote() -> str:
    """Return a random job completion quote."""
    return random.choice(JOB_COMPLETION_QUOTES)
